###########################################################################
#
# Generated by : Version 11.0 Build 157 04/27/2011 SJ Full Version
#
# Project      : DE2_TV
# Revision     : DE2_TV
#
# Date         : Thu Nov 17 16:13:55 EST 2011
#
###########################################################################
 
 
# WARNING: Expected ENABLE_CLOCK_LATENCY to be set to 'ON', but it is set to 'OFF'
#          In SDC, create_generated_clock auto-generates clock latency
#
# ------------------------------------------
#
# Create generated clocks based on PLLs
derive_pll_clocks -use_tan_name
#
# ------------------------------------------


# Original Clock Setting Name: OSC_50
create_clock -period "20.000 ns" \
             -name {OSC_50} {OSC_50}
# ---------------------------------------------


# Original Clock Setting Name: TD_CLK
create_clock -period "37.037 ns" \
             -name {TD_CLK} {TD_CLK}
# ---------------------------------------------


# Original Clock Setting Name: OSC_27
create_clock -period "37.037 ns" \
             -name {OSC_27} {OSC_27}
# ---------------------------------------------


# Original Clock Setting Name: DLY0
# WARNING: Ignoring OFFSET_FROM_BASE_CLOCK assignment for clock 'DLY0'
create_generated_clock -divide_by 16384 -multiply_by 1  \
                       -source OSC_50 \
                       -name {Reset_Delay:u3|oRST_0} \
                       {Reset_Delay:u3|oRST_0}
# ---------------------------------------------

# ** Clock Latency
#    -------------

# ** Clock Uncertainty
#    -----------------

# ** Multicycles
#    -----------
# ** Cuts
#    ----

# ** Input/Output Delays
#    -------------------




# ** Tpd requirements
#    ----------------

# ** Setup/Hold Relationships
#    ------------------------

# ** Tsu/Th requirements
#    -------------------


# ** Tco/MinTco requirements
#    -----------------------



# ---------------------------------------------
# The following clock group is added to try to 
# match the behavior of:
#   CUT_OFF_PATHS_BETWEEN_CLOCK_DOMAINS = ON
# ---------------------------------------------

set_clock_groups -asynchronous \
                 -group { \
                       TD_CLK \
                        } \
                 -group { \
                       OSC_50 \
                       Reset_Delay:u3|oRST_0 \
                        } \
                 -group { \
                       Sdram_Control_4Port:u6|Sdram_PLL:sdram_pll1|altpll:altpll_component|_clk0 \
                       Sdram_Control_4Port:u6|Sdram_PLL:sdram_pll1|altpll:altpll_component|_clk1 \
                       Sdram_Control_4Port:u6|Sdram_PLL:sdram_pll1|altpll:altpll_component|_clk2 \
                       OSC_27 \
                        } \

# ---------------------------------------------

